### ISSUE TITLE
iOS AV audio player volume is 0.0 to 1.0

### ISSUE THREAD

**Issue by ltaylor934** [srkrathore/AudioPlayEx#2]
I used your AudioPlayEx code, but I found a problem:
You set the volume of an audio player in iOS to 100f, but the range is 0.0f to 1.0f. At 100f, it sounded terrible. I changed it to 1.0f, and it sounded good.
            // _player.Volume =100f;
            _player.Volume = 1.0f; // range is 0.0 to 1.0

**Comment by techierathore** [comment]
it depends on the sound file you play, the file I used for testing was working fine at the value of 100f. if your sound file sound better at 1.0f then you can use it.
